[lxd-import] lxd/firewall: Fix nftables ACL template
Network interface name must be double-quoted to avoid
collisions with the nftables syntax.

For example a bridge network called `rt` will cause the following error prior to this commit:
```
Error: syntax error, unexpected rt
           iifname rt jump acl.rt
                   ^^
```
when trying to set ACL:
`incus network set rt security.acls="rt-acl"`
because `rt` is a restricted token in the nftables syntax:
https://wiki.nftables.org/wiki-nftables/index.php/Quick_reference-nftables_in_10_minutes#Rt

Signed-off-by: Rafal Borczuch <rafalq.b@gmail.com>