[lxd-import] test/migration: use a smaller ISO file
Apparently we are running tight on space and that's causing test failures:

> timeout --foreground 120 /home/runner/go/bin/incus storage volume copy l1:incustest-3vW/iso1 l2:incustest-fut/iso1 --verbose
> ...
> time="2023-08-02T10:58:47Z" level=info msg="Migration channels disconnected on target" pool=incustest-fut project=default push=false volume=iso1
> Error: Failed storage volume creation: Error transferring storage volume: Error copying from migration connection to "/dev/zvol/incustest-fut/custom/default_iso1.iso": write /dev/zvol/incustest-fut/custom/default_iso1.iso: no space left on device

I tried multiple size for ISO files (1, 2, 4, 8) and only
8MiB was reliable. Smaller sizes would always fail on some tests
with the dir backend.

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>